services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gym
      MYSQL_USER: deog1 # Cambiar por fmpp3
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306" # Exponer el puerto 3306 del contenedor al host
    volumes:
      - gym_mysql_data:/var/lib/mysql
    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080" # Adminer estará accesible en localhost:8080
    networks:
      - my_network

volumes:
  gym_mysql_data:

networks:
  my_network:
